--[[

	--Made by Squiz (http://steamcommunity.com/id/giveitasquiz/)
	-- Add me for any questions or to reuse ^-^

]]-- 

cpVoicesTeam = {
"Police Recruit",
"Police Lt.",
"Warden",
"Police Sgt.",
"Police Cpt.",
"Scanner",
"Police Com.",
"MPF"}

cpComs = {}

function addCom(command,sounddir) 
    cpComs[command] = sounddir
end

addCom("404zone","npc/metropolice/vo/404zone.wav")
addCom( "sweeping", "npc/metropolice/hiding02.wav" )
addCom( "position", "npc/metropolice/hiding03.wav" ) 
addCom( "lock", "npc/metropolice/hiding04.wav" ) 
addCom( "isolate", "npc/metropolice/hiding05.wav" ) 
addCom( "takedown", "npc/metropolice/takedown.wav" ) 
addCom( "11-99", "npc/metropolice/vo/11-99officerneedsassistance.wav" )
addCom( "404", "npc/metropolice/vo/404zone.wav" ) 
addCom( "visual", "npc/metropolice/vo/acquiringonvisual.wav") 
addCom( "administer", "npc/metropolice/vo/administer.wav") 
addCom( "yes", "npc/metropolice/vo/affirmative.wav") 
addCom( "yes2", "npc/metropolice/vo/affirmative2.wav") 
addCom( "airwatch", "npc/metropolice/vo/airwatchsubjectis505.wav") 
addCom( "youcango", "npc/metropolice/vo/allrightyoucango.wav") 
addCom( "allunitsbol34sat", "npc/metropolice/vo/allunitsbol34sat.wav") 
addCom( "closeonsuspect", "npc/metropolice/vo/allunitscloseonsuspect.wav") 
addCom( "allunitscode2", "npc/metropolice/vo/allunitscode2.wav") 
addCom( "allunitsmaintainthiscp", "npc/metropolice/vo/allunitsmaintainthiscp.wav") 
addCom( "allunitsmovein", "npc/metropolice/vo/allunitsmovein.wav") 
addCom( "suspectlocation", "npc/metropolice/vo/allunitsreportlocationsuspect.wav") 
addCom( "allunitsrespondcode3", "npc/metropolice/vo/allunitsreportlocationsuspect.wav") 
addCom( "amputate", "npc/metropolice/vo/amputate.wav") 
addCom( "anticitizen", "npc/metropolice/vo/anticitizen.wav") 
addCom( "anyonepickup647e", "npc/metropolice/vo/anyonepickup647e.wav") 
addCom( "apply", "npc/metropolice/vo/apply.wav") 
addCom( "assaultpointsecureadvance", "npc/metropolice/vo/assaultpointsecureadvance.wav") 
addCom( "atcheckpoint", "npc/metropolice/vo/atcheckpoint.wav") 
addCom( "backmeupimout", "npc/metropolice/vo/backmeupImout.wav") 
addCom( "backup", "npc/metropolice/vo/backup.wav") 
addCom( "block", "npc/metropolice/vo/block.wav") 
addCom( "blockisholdingcohesive", "npc/metropolice/vo/blockisholdingcohesive.wav") 
addCom( "breakhiscover", "npc/metropolice/vo/breakhiscover.wav") 
addCom( "bugs", "npc/metropolice/vo/bugs.wav") 
addCom( "bugsontheloose", "npc/metropolice/vo/bugsontheloose.wav")
addCom( "canal", "npc/metropolice/vo/canal.wav") 
addCom( "canalblock", "npc/metropolice/vo/canalblock.wav") 
addCom( "catchthatbliponstabilization", "npc/metropolice/vo/catchthatbliponstabilization.wav") 
addCom( "cauterize", "npc/metropolice/vo/cauterize.wav") 
addCom( "checkformiscount", "npc/metropolice/vo/checkformiscount.wav") 
addCom( "haha", "npc/metropolice/vo/chuckle.wav") 
addCom( "citizen", "npc/metropolice/vo/citizen.wav") 
addCom( "citizensummoned", "npc/metropolice/vo/citizensummoned.wav") 
addCom( "classifyasdbthisblockready", "npc/metropolice/vo/classifyasdbthisblockready.wav") 
addCom( "clearandcode100", "npc/metropolice/vo/clearandcode100.wav") 
addCom( "clearno647no10-107", "npc/metropolice/vo/clearno647no10-107.wav") 
addCom( "code7", "npc/metropolice/vo/code7.wav") 
addCom( "code100", "npc/metropolice/vo/code100.wav") 
addCom( "condemnedzone", "npc/metropolice/vo/condemnedzone.wav") 
addCom( "confirmadw", "npc/metropolice/vo/confirmadw.wav") 
addCom( "confirmpriority1sighted", "npc/metropolice/vo/confirmpriority1sighted.wav") 
addCom( "contactwith243suspect", "npc/metropolice/vo/contactwith243suspect.wav") 
addCom( "contactwithpriority2", "npc/metropolice/vo/contactwithpriority2.wav") 
addCom( "control100percent", "npc/metropolice/vo/control100percent.wav") 
addCom( "controlsection", "npc/metropolice/vo/controlsection.wav") 
addCom( "converging", "npc/metropolice/vo/converging.wav") 
addCom( "copy", "npc/metropolice/vo/copy.wav") 
addCom( "covermegoingin", "npc/metropolice/vo/covermegoingin.wav") 
addCom( "cpbolforthat243", "npc/metropolice/vo/cpbolforthat243.wav") 
addCom( "cpiscompromised", "npc/metropolice/vo/cpiscompromised.wav") 
addCom( "cpisoverrunwehavenocontainment", "npc/metropolice/vo/cpisoverrunwehavenocontainment.wav") 
addCom( "cprequestsallunitsreportin", "npc/metropolice/vo/cprequestsallunitsreportin.wav") 
addCom( "cpweneedtoestablishaperimeterat", "npc/metropolice/vo/cpweneedtoestablishaperimeterat.wav") 
addCom( "criminaltrespass", "npc/metropolice/vo/criminaltrespass63.wav") 
addCom( "dbcountis", "npc/metropolice/vo/dbcountis.wav") 
addCom( "defender", "npc/metropolice/vo/defender.wav") 
addCom( "deservicedarea", "npc/metropolice/vo/deservicedarea.wav") 
addCom( "designatesuspectas", "npc/metropolice/vo/designatesuspectas.wav") 
addCom( "destroythatcover", "npc/metropolice/vo/destroythatcover.wav")
addCom( "dismountinghardpoint", "npc/metropolice/vo/dismountinghardpoint.wav")
addCom( "10-78", "npc/metropolice/vo/dispatchIneed10-78.wav")
addCom( "dispreportssuspectincursion", "npc/metropolice/vo/dispreportssuspectincursion.wav")
addCom( "dispupdatingapb", "npc/metropolice/vo/dispupdatingapb.wav")
addCom( "distributionblock", "npc/metropolice/vo/distributionblock.wav")
addCom( "document", "npc/metropolice/vo/document.wav")
addCom( "dontmove", "npc/metropolice/vo/dontmove.wav")
addCom( "8", "npc/metropolice/vo/eight.wav")
addCom( "18", "npc/metropolice/vo/eighteen.wav")
addCom( "80", "npc/metropolice/vo/eighty.wav")
addCom( "11", "npc/metropolice/vo/eleven.wav")
addCom( "establishnewcp", "npc/metropolice/vo/establishnewcp.wav")
addCom( "examine", "npc/metropolice/vo/examine.wav")
addCom( "expired", "npc/metropolice/vo/expired.wav")
addCom( "external", "npc/metropolice/vo/externaljurisdiction.wav")
addCom( "15", "npc/metropolice/vo/fifteen.wav")
addCom( "50", "npc/metropolice/vo/fifty.wav")
addCom( "finalverdict", "npc/metropolice/vo/finalverdictadministered.wav")
addCom( "finalwarning", "npc/metropolice/vo/finalwarning.wav")
addCom( "firetodislocateinterpose", "npc/metropolice/vo/firetodislocateinterpose.wav")
addCom( "firingtoexposetarget", "npc/metropolice/vo/firingtoexposetarget.wav") 
addCom( "1stwarningmove", "npc/metropolice/vo/firstwarningmove.wav")
addCom( "5", "npc/metropolice/vo/five.wav")
addCom( "4", "npc/metropolice/vo/four.wav")
addCom( "14", "npc/metropolice/vo/fourteen.wav")
addCom( "40", "npc/metropolice/vo/fourty.wav")
addCom( "freeman", "npc/metropolice/vo/freeman.wav")
addCom( "freenecrotics", "npc/metropolice/vo/freenecrotics.wav")
addCom( "get11-44inboundcleaningup", "npc/metropolice/vo/get11-44inboundcleaningup.wav")
addCom( "getdown", "npc/metropolice/vo/getdown.wav")
addCom( "getoutofhere", "npc/metropolice/vo/getoutofhere.wav")
addCom( "goingtotakealook", "npc/metropolice/vo/goingtotakealook.wav")
addCom( "gota10-107sendairwatch", "npc/metropolice/vo/gota10-107sendairwatch.wav")
addCom( "gothimagainsuspect10-20at", "npc/metropolice/vo/gothimagainsuspect10-20at.wav")
addCom( "gotoneaccomplicehere", "npc/metropolice/vo/gotoneaccomplicehere.wav")
addCom( "gotsuspect1here", "npc/metropolice/vo/gotsuspect1here.wav")
addCom( "grenade", "npc/metropolice/vo/grenade.wav")
addCom( "hardpointscanning", "npc/metropolice/vo/hardpointscanning.wav")
addCom( "help", "npc/metropolice/vo/help.wav")
addCom( "hero", "npc/metropolice/vo/hero.wav")
addCom( "hesgone148", "npc/metropolice/vo/hesgone148.wav")
addCom( "hesrunning", "npc/metropolice/vo/hesrunning.wav")
addCom( "hesupthere", "npc/metropolice/vo/hesupthere.wav")
addCom( "hidinglastseenatrange", "npc/metropolice/vo/hidinglastseenatrange.wav")
addCom( "highpriorityregion", "npc/metropolice/vo/highpriorityregion.wav")
addCom( "highpriorityregion", "npc/metropolice/vo/highpriorityregion.wav")
addCom( "holdingon10-14duty", "npc/metropolice/vo/holdingon10-14duty.wav")
addCom( "holdit", "npc/metropolice/vo/holdit.wav")
addCom( "holdthisposition", "npc/metropolice/vo/holdthisposition.wav")
addCom( "Ihave10-30my10-20responding", "npc/metropolice/vo/Ihave10-30my10-20responding.wav")
addCom( "industrialzone", "npc/metropolice/vo/industrialzone.wav")
addCom( "infection", "npc/metropolice/vo/infection.wav")
addCom( "infestedzone", "npc/metropolice/vo/infestedzone.wav")
addCom( "inject", "npc/metropolice/vo/inject.wav")
addCom( "innoculate", "npc/metropolice/vo/innoculate.wav")
addCom( "inposition", "npc/metropolice/vo/inposition.wav") 
addCom( "inpositionathardpoint", "npc/metropolice/vo/inpositionathardpoint.wav")
addCom( "inpositiononeready", "npc/metropolice/vo/inpositiononeready.wav")
addCom( "intercede", "npc/metropolice/vo/intercede.wav")
addCom( "interlock", "npc/metropolice/vo/interlock.wav")
addCom( "investigate", "npc/metropolice/vo/investigate.wav")
addCom( "investigating10-103", "npc/metropolice/vo/investigating10-103.wav")
addCom( "is10-108", "npc/metropolice/vo/is10-108.wav")
addCom( "is415b", "npc/metropolice/vo/is415b.wav")
addCom( "isaidmovealong", "npc/metropolice/vo/Isaidmovealong.wav")
addCom( "isathardpointreadytoprosecute", "npc/metropolice/vo/isathardpointreadytoprosecute.wav")
addCom( "isclosingonsuspect", "npc/metropolice/vo/isclosingonsuspect.wav")
addCom( "isdown", "npc/metropolice/vo/isdown.wav")
addCom( "isgo", "npc/metropolice/vo/isgo.wav")
addCom( "ismovingin", "npc/metropolice/vo/ismovingin.wav")
addCom( "isolate", "npc/metropolice/vo/isolate.wav")
addCom( "ispassive", "npc/metropolice/vo/ispassive.wav")
addCom( "isreadytogo", "npc/metropolice/vo/isreadytogo.wav")
addCom( "ticket", "npc/metropolice/vo/issuingmalcompliantcitation.wav")
addCom( "Ivegot408hereatlocation", "npc/metropolice/vo/Ivegot408hereatlocation.wav")
addCom( "jury", "npc/metropolice/vo/jury.wav")
addCom( "keepmoving", "npc/metropolice/vo/keepmoving.wav")
addCom( "king", "npc/metropolice/vo/king.wav")
addCom( "level3civilprivacyviolator", "npc/metropolice/vo/level3civilprivacyviolator.wav")
addCom( "line", "npc/metropolice/vo/line.wav")
addCom( "localcptreportstatus", "npc/metropolice/vo/localcptreportstatus.wav")
addCom( "location", "npc/metropolice/vo/location.wav")
addCom( "lockyourposition", "npc/metropolice/vo/lockyourposition.wav")
addCom( "lookingfortrouble", "npc/metropolice/vo/lookingfortrouble.wav")
addCom( "lookout", "npc/metropolice/vo/lookout.wav")  
addCom( "lookoutrogueviscerator", "npc/metropolice/vo/lookoutrogueviscerator.wav")
addCom( "looseparasitics", "npc/metropolice/vo/looseparasitics.wav")
addCom( "loyaltycheckfailure", "npc/metropolice/vo/loyaltycheckfailure.wav")
addCom( "1020", "npc/metropolice/vo/malcompliant10107my1020.wav")
addCom( "malignant", "npc/metropolice/vo/malignant.wav")
addCom( "matchonapblikeness", "npc/metropolice/vo/matchonapblikeness.wav")
addCom( "meters", "npc/metropolice/vo/meters.wav")
addCom( "minorhitscontinuing", "npc/metropolice/vo/minorhitscontinuing.wav")
addCom( "move", "npc/metropolice/vo/move.wav")
addCom( "movealong", "npc/metropolice/vo/movealong.wav")
addCom( "movealong3", "npc/metropolice/vo/movealong3.wav")
addCom( "movebackrightnow", "npc/metropolice/vo/movebackrightnow.wav")
addCom( "moveit", "npc/metropolice/vo/moveit.wav")
addCom( "moveit2", "npc/metropolice/vo/moveit2.wav")
addCom( "arrest", "npc/metropolice/vo/movetoarrestpositions.wav")
addCom( "movingtocover", "npc/metropolice/vo/movingtocover.wav")
addCom( "movingtohardpoint", "npc/metropolice/vo/movingtohardpoint.wav")
addCom( "movingtohardpoint2", "npc/metropolice/vo/movingtohardpoint2.wav")
addCom( "necrotics", "npc/metropolice/vo/necrotics.wav")
addCom( "needanyhelp", "npc/metropolice/vo/needanyhelpwiththisone.wav")
addCom( "9", "npc/metropolice/vo/nine.wav")
addCom( "19", "npc/metropolice/vo/nineteen.wav")
addCom( "90", "npc/metropolice/vo/ninety.wav")
addCom( "nocontact", "npc/metropolice/vo/nocontact.wav")
addCom( "noncitizen", "npc/metropolice/vo/noncitizen.wav")
addCom( "nonpatrolregion", "npc/metropolice/vo/nonpatrolregion.wav")
addCom( "non-taggedviromeshere", "npc/metropolice/vo/non-taggedviromeshere.wav")
addCom( "novisualonupi", "npc/metropolice/vo/novisualonupi.wav")
addCom( "nowgetoutofhere", "npc/metropolice/vo/nowgetoutofhere.wav")
addCom( "officerdownIam10-99", "npc/metropolice/vo/officerdownIam10-99.wav")
addCom( "officerneedshelp", "npc/metropolice/vo/officerneedsassistance.wav")
addCom( "officerneedshelp", "npc/metropolice/vo/officerneedshelp.wav")
addCom( "officerunderfiretakingcover", "npc/metropolice/vo/officerunderfiretakingcover.wav")
addCom( "officerdowncode3tomy10-20", "npc/metropolice/vo/officerdowncode3tomy10-20.wav")
addCom( "1", "npc/metropolice/vo/one.wav")
addCom( "100", "npc/metropolice/vo/onehundred.wav")
addCom( "outbreak", "npc/metropolice/vo/outbreak.wav")
addCom( "outlandbioticinhere", "npc/metropolice/vo/outlandbioticinhere.wav")
addCom( "outlandzone", "npc/metropolice/vo/outlandzone.wav")
addCom( "pacifying", "npc/metropolice/vo/pacifying.wav")
addCom( "patrol", "npc/metropolice/vo/patrol.wav")
addCom( "pickingupnoncorplexindy", "npc/metropolice/vo/pickingupnoncorplexindy.wav")
addCom( "pickupthecan1", "npc/metropolice/vo/pickupthecan1.wav")
addCom( "pickupthecan2", "npc/metropolice/vo/pickupthecan2.wav")
addCom( "pickupthecan3", "npc/metropolice/vo/pickupthecan3.wav")
addCom( "positiontocontain", "npc/metropolice/vo/positiontocontain.wav")
addCom( "possible10-103alerttagunits", "npc/metropolice/vo/possible10-103alerttagunits.wav")
addCom( "possible404here", "npc/metropolice/vo/possible404here.wav")
addCom( "possible647erequestairwatch", "npc/metropolice/vo/possible647erequestairwatch.wav")
addCom( "possiblelevel3civilprivacyviolator", "npc/metropolice/vo/possiblelevel3civilprivacyviolator.wav")
addCom( "preparefor1015", "npc/metropolice/vo/preparefor1015.wav")
addCom( "prepareforjudgement", "npc/metropolice/vo/prepareforjudgement.wav")
addCom( "preparingtojudge10-107", "npc/metropolice/vo/preparingtojudge10-107.wav")
addCom( "preserve", "npc/metropolice/vo/preserve.wav")
addCom( "pressure", "npc/metropolice/vo/pressure.wav")
addCom( "priority2anticitizenhere", "npc/metropolice/vo/priority2anticitizenhere.wav")
addCom( "proceedtocheckpoints", "npc/metropolice/vo/proceedtocheckpoints.wav")
addCom( "productionblock", "npc/metropolice/vo/productionblock.wav")
addCom( "prosecute", "npc/metropolice/vo/prosecute.wav")
addCom( "protectioncomplete", "npc/metropolice/vo/protectioncomplete.wav")
addCom( "ptatlocationreport", "npc/metropolice/vo/ptatlocationreport.wav")
addCom( "ptgoagain", "npc/metropolice/vo/ptgoagain.wav")
addCom( "putitinthetrash1", "npc/metropolice/vo/putitinthetrash1.wav")
addCom( "putitinthetrash2", "npc/metropolice/vo/putitinthetrash2.wav")
addCom( "quick", "npc/metropolice/vo/quick.wav")
addCom( "readytoamputate", "npc/metropolice/vo/readytoamputate.wav")
addCom( "readytojudge", "npc/metropolice/vo/readytojudge.wav")
addCom( "readytoprosecute", "npc/metropolice/vo/readytoprosecute.wav")
addCom( "readytoprosecutefinalwarning", "npc/metropolice/vo/readytoprosecutefinalwarning.wav")
addCom( "reportsightingsaccomplices", "npc/metropolice/vo/.wav")
addCom( "repurposedarea", "npc/metropolice/vo/.wav")
addCom( "requestsecondaryviscerator", "npc/metropolice/vo/.wav")
addCom( "residentialblock", "npc/metropolice/vo/.wav")
addCom( "responding2", "npc/metropolice/vo/responding2.wav")
addCom( "restrict", "npc/metropolice/vo/restrict.wav")
addCom( "restrictedblock", "npc/metropolice/vo/restrictedblock.wav")
addCom( "rodgerthat", "npc/metropolice/vo/rodgerthat.wav")
addCom( "roller", "npc/metropolice/vo/roller.wav")
addCom( "runninglowonverdicts", "npc/metropolice/vo/runninglowonverdicts.wav")
addCom( "sacrificecode1maintaincp", "npc/metropolice/vo/sacrificecode1maintaincp.wav")
addCom( "search", "npc/metropolice/vo/search.wav")
addCom( "searchingforsuspect", "npc/metropolice/vo/searchingforsuspect.wav")
addCom( "2ndwarning", "npc/metropolice/vo/secondwarning.wav")
addCom( "sector", "npc/metropolice/vo/sector.wav")
addCom( "sentencedelivered", "npc/metropolice/vo/sentencedelivered.wav")
addCom( "serve", "npc/metropolice/vo/serve.wav")
addCom( "7", "npc/metropolice/vo/seven.wav")
addCom( "17", "npc/metropolice/vo/seventeen.wav")
addCom( "70", "npc/metropolice/vo/seventy.wav")
addCom( "shit", "npc/metropolice/vo/shit.wav")
addCom( "shotsfiredhostilemalignants", "npc/metropolice/vo/shotsfiredhostilemalignants.wav")
addCom( "6", "npc/metropolice/vo/six.wav")
addCom( "16", "npc/metropolice/vo/sixteen.wav")
addCom( "60", "npc/metropolice/vo/sixty.wav")
addCom( "sociocide", "npc/metropolice/vo/sociocide.wav")
addCom( "stabilizationjurisdiction", "npc/metropolice/vo/stabilizationjurisdiction.wav")
addCom( "standardloyaltycheck", "npc/metropolice/vo/standardloyaltycheck.wav")
addCom( "stationblock", "npc/metropolice/vo/stationblock.wav")
addCom( "sterilize", "npc/metropolice/vo/sterilize.wav")
addCom( "stick", "npc/metropolice/vo/stick.wav")
addCom( "stillgetting647e", "npc/metropolice/vo/stillgetting647e.wav")
addCom( "stormsystem", "npc/metropolice/vo/stormsystem.wav")
addCom( "subject", "npc/metropolice/vo/subject.wav")
addCom( "subjectis505", "npc/metropolice/vo/subjectis505.wav")
addCom( "subjectisnowhighspeed", "npc/metropolice/vo/subjectisnowhighspeed.wav")
addCom( "supsecthasmovednowto", "npc/metropolice/vo/supsecthasmovednowto.wav")
addCom( "suspect11-6my1020is", "npc/metropolice/vo/suspect11-6my1020is.wav")
addCom( "suspectinstormrunoff", "npc/metropolice/vo/suspectinstormrunoff.wav")
addCom( "suspectisbleeding", "npc/metropolice/vo/suspectisbleeding.wav")
addCom( "suspectlocationunknown", "npc/metropolice/vo/suspectlocationunknown.wav")
addCom( "suspectusingrestrictedcanals", "npc/metropolice/vo/suspectusingrestrictedcanals.wav")
addCom( "suspend", "npc/metropolice/vo/suspend.wav")
addCom( "tag10-91d", "npc/metropolice/vo/tag10-91d.wav")
addCom( "tagonebug", "npc/metropolice/vo/tagonebug.wav")
addCom( "tagonenecrotic", "npc/metropolice/vo/tagonenecrotic.wav")
addCom( "tagoneparasitic", "npc/metropolice/vo/tagoneparasitic.wav")
addCom( "takecover", "npc/metropolice/vo/takecover.wav")
addCom( "tap", "npc/metropolice/vo/tap.wav")
addCom( "teaminpositionadvance", "npc/metropolice/vo/teaminpositionadvance.wav")
addCom( "10", "npc/metropolice/vo/ten.wav")
addCom( "10-2", "npc/metropolice/vo/ten2.wav")
addCom( "10-4", "npc/metropolice/vo/ten4.wav")
addCom( "ten8standingby", "npc/metropolice/vo/ten8standingby.wav")
addCom( "ten91dcountis", "npc/metropolice/vo/ten91dcountis.wav")
addCom( "ten97", "npc/metropolice/vo/ten97.wav")
addCom( "ten97suspectisgoa", "npc/metropolice/vo/ten97suspectisgoa.wav")
addCom( "ten97suspectisgoa", "npc/metropolice/vo/ten97suspectisgoa.wav")
addCom( "tenzerovisceratorishunting", "npc/metropolice/vo/tenzerovisceratorishunting.wav")
addCom( "terminalrestrictionzone", "npc/metropolice/vo/terminalrestrictionzone.wav")
addCom( "thatsagrenade", "npc/metropolice/vo/thatsagrenadewav")
addCom( "therehegoeshesat", "npc/metropolice/vo/therehegoeshesat.wav")
addCom( "thereheis", "npc/metropolice/vo/thereheis.wav")
addCom( "13", "npc/metropolice/vo/thirteen.wav")
addCom( "30", "npc/metropolice/vo/thirty.wav")
addCom( "thisisyoursecondwarning", "npc/metropolice/vo/thisisyoursecondwarning.wav")
addCom( "3", "npc/metropolice/vo/three.wav")
addCom( "300", "npc/metropolice/vo/threehundred.wav")
addCom( "transitblock", "npc/metropolice/vo/transitblock.wav")
addCom( "12", "npc/metropolice/vo/twelve.wav")
addCom( "20", "npc/metropolice/vo/twenty.wav")
addCom( "2", "npc/metropolice/vo/two.wav")
addCom( "200", "npc/metropolice/vo/twohundred.wav")
addCom( "union", "npc/metropolice/vo/union.wav")
addCom( "unitis10-8standingby", "npc/metropolice/vo/unitis10-8standingby.wav")
addCom( "unitis10-65", "npc/metropolice/vo/unitis10-65.wav")
addCom( "unitisonduty10-8", "npc/metropolice/vo/unitisonduty10-8.wav")
addCom( "unitreportinwith10-25suspect", "npc/metropolice/vo/unitreportinwith10-25suspect.wav")
addCom( "unlawfulentry", "npc/metropolice/vo/unlawfulentry603.wav")
addCom( "upi", "npc/metropolice/vo/upi.wav")
addCom( "utlsuspect", "npc/metropolice/vo/utlsuspect.wav")
addCom( "utlthatsuspect", "npc/metropolice/vo/utlthatsuspect.wav")
addCom( "vacatecitizen", "npc/metropolice/vo/vacatecitizen.wav")
addCom( "vice", "npc/metropolice/vo/vice.wav")
addCom( "victor", "npc/metropolice/vo/victor.wav")
addCom( "visceratordeployed", "npc/metropolice/vo/visceratordeployed.wav")
addCom( "visceratorisoc", "npc/metropolice/vo/visceratorisoc.wav")
addCom( "visceratorisoffgrid", "npc/metropolice/vo/visceratorisoffgrid.wav")
addCom( "wasteriver", "npc/metropolice/vo/wasteriver.wav")
addCom( "watchit", "npc/metropolice/vo/watchit.wav")
addCom( "wearesociostablethislocation", "npc/metropolice/vo/wearesociostablethislocation.wav")
addCom( "wegotadbherecancel10-102", "npc/metropolice/vo/wegotadbherecancel10-102.wav")
addCom( "wehavea10-108", "npc/metropolice/vo/wehavea10-108.wav")
addCom( "workforceintake", "npc/metropolice/vo/workforceintake.wav")
addCom( "xray", "npc/metropolice/vo/xray.wav")
addCom( "yellow", "npc/metropolice/vo/yellow.wav")
addCom( "youknockeditover", "npc/metropolice/vo/youknockeditover.wav")
addCom( "verdict", "npc/metropolice/vo/youwantamalcomplianceverdict.wav")
addCom( "0", "npc/metropolice/vo/zero.wav")
addCom( "zone", "npc/metropolice/vo/zone.wav")
addCom("overwatchconfirmhvtcontained","npc/combine_soldier/vo/overwatchconfirmhvtcontained.wav")
addCom("niner","npc/combine_soldier/vo/niner.wav")
addCom("six","npc/combine_soldier/vo/six.wav")
addCom("jet","npc/combine_soldier/vo/jet.wav")
addCom("dash","npc/combine_soldier/vo/dash.wav")
addCom("overwatchteamisdown","npc/combine_soldier/vo/overwatchteamisdown.wav")
addCom("overrun","npc/combine_soldier/vo/overwatchsectoroverrun.wav")
addCom("stabilizationteamhassector","npc/combine_soldier/vo/stabilizationteamhassector.wav")
addCom("hammer","npc/combine_soldier/vo/hammer.wav")
addCom("eight","npc/combine_soldier/vo/eight.wav")
addCom("overwatchrequestreserveactivation","npc/combine_soldier/vo/overwatchrequestreserveactivation.wav")
addCom("hostilesinbound","npc/combine_soldier/vo/readyweaponshostilesinbound.wav")
addCom("ovewatchorders3ccstimboost","npc/combine_soldier/vo/ovewatchorders3ccstimboost.wav")
addCom("overwatchrequestwinder","npc/combine_soldier/vo/overwatchrequestwinder.wav")
addCom("ispromoted","npc/combine_soldier/vo/isfieldpromoted.wav")
addCom("stabilizationteamholding","npc/combine_soldier/vo/stabilizationteamholding.wav")
addCom("one","npc/combine_soldier/vo/one.wav")
addCom("turnoffcoms","npc/combine_soldier/vo/off2.wav")
addCom("isfinalteamunitbackup","npc/combine_soldier/vo/isfinalteamunitbackup.wav")
addCom("reforcement","npc/combine_soldier/vo/overwatchrequestreinforcement.wav")
addCom("sectorissecurenovison","npc/combine_soldier/vo/sectorissecurenovison.wav")
addCom("fist","npc/combine_soldier/vo/fist.wav")
addCom("swarmoutbreakinsector","npc/combine_soldier/vo/swarmoutbreakinsector.wav")
addCom("skyshieldreportslostcontact","npc/combine_soldier/vo/skyshieldreportslostcontact.wav")
addCom("outbreakstatusiscode","npc/combine_soldier/vo/outbreakstatusiscode.wav")
addCom("gridsundown46","npc/combine_soldier/vo/gridsundown46.wav")
addCom("targetwaskilled","npc/combine_soldier/vo/overwatchtarget1sterilized.wav")
addCom("callcontacttarget1","npc/combine_soldier/vo/callcontacttarget1.wav")
addCom("stayalert","npc/combine_soldier/vo/stayalertreportsightlines.wav")
addCom("targetcontained","npc/combine_soldier/vo/overwatchtargetcontained.wav")
addCom("designatetargetas","npc/combine_soldier/vo/designatetargetas.wav")
addCom("escapee","npc/combine_soldier/vo/prioritytwoescapee.wav")
addCom("contactconfirmed","npc/combine_soldier/vo/contactconfirmprosecuting.wav")
addCom("sectionlockupdash4","npc/combine_soldier/vo/sectionlockupdash4.wav")
addCom("motioncheckallradials","npc/combine_soldier/vo/motioncheckallradials.wav")
addCom("code","npc/combine_soldier/vo/isholdingatcode.wav")
addCom("callcontactparasitics","npc/combine_soldier/vo/callcontactparasitics.wav")
addCom("overwatchrequestskyshield","npc/combine_soldier/vo/overwatchrequestskyshield.wav")
addCom("confirmsectornotsterile","npc/combine_soldier/vo/confirmsectornotsterile.wav")
addCom("turnoffcoms2","npc/combine_soldier/vo/off1.wav")
addCom("allclear","npc/combine_soldier/vo/reportallpositionsclear.wav")
addCom("sectorisnotsecure","npc/combine_soldier/vo/sectorisnotsecure.wav")
addCom("prepare","npc/combine_soldier/vo/prepforcontact.wav")
addCom("priority1objective","npc/combine_soldier/vo/priority1objective.wav")
addCom("executingfullresponse","npc/combine_soldier/vo/executingfullresponse.wav")
addCom("onedutyvacated","npc/combine_soldier/vo/onedutyvacated.wav")
addCom("anticitizen1","npc/combine_soldier/vo/anticitizenone.wav")
addCom("hesdead","npc/combine_soldier/vo/hasnegativemovement.wav")
addCom("extractorislive","npc/combine_soldier/vo/extractorislive.wav")
addCom("reportallradialsfree","npc/combine_soldier/vo/reportallradialsfree.wav")
addCom("ripcord","npc/combine_soldier/vo/ripcordripcord.wav")
addCom("bouncer","npc/combine_soldier/vo/bouncerbouncer.wav")
addCom("engagedincleanup","npc/combine_soldier/vo/engagedincleanup.wav")
addCom("block31mace","npc/combine_soldier/vo/block31mace.wav")
addCom("fixlights","npc/combine_soldier/vo/fixsightlinesmovein.wav")
addCom("containmentproceeding","npc/combine_soldier/vo/containmentproceeding.wav")
addCom("block64jet","npc/combine_soldier/vo/block64jet.wav")
addCom("gosharp","npc/combine_soldier/vo/gosharpgosharp.wav")
addCom("wegothim","npc/combine_soldier/vo/affirmativewegothimnow.wav")
addCom("hardenthatposition","npc/combine_soldier/vo/hardenthatposition.wav")
addCom("readyextractors","npc/combine_soldier/vo/readyextractors.wav")
addCom("goactiveintercept","npc/combine_soldier/vo/goactiveintercept.wav")
addCom("onecontained","npc/combine_soldier/vo/onecontained.wav")
addCom("sightisclear","npc/combine_soldier/vo/sightlineisclear.wav")
addCom("requeststimdose","npc/combine_soldier/vo/requeststimdose.wav")
addCom("extractoraway","npc/combine_soldier/vo/extractoraway.wav")
addCom("requestdoctor","npc/combine_soldier/vo/requestmedical.wav")
addCom("bodypackholding","npc/combine_soldier/vo/bodypackholding.wav")
addCom("contactconfirmed","npc/combine_soldier/vo/contactconfim.wav")
addCom("isatcode","npc/combine_soldier/vo/isatcode.wav")
addCom("fullactive","npc/combine_soldier/vo/fullactive.wav")
addCom("lostcontact","npc/combine_soldier/vo/lostcontact.wav")
addCom("antiseptic","npc/combine_soldier/vo/antiseptic.wav")
addCom("callhotpoint","npc/combine_soldier/vo/callhotpoint.wav")
addCom("reportingclear","npc/combine_soldier/vo/reportingclear.wav")
addCom("standingby","npc/combine_soldier/vo/standingby].wav")
addCom("infected","npc/combine_soldier/vo/infected.wav")
addCom("readycharges","npc/combine_soldier/vo/readycharges.wav")
addCom("administer","npc/combine_soldier/vo/administer.wav")
addCom("noviscon","npc/combine_soldier/vo/noviscon.wav")
addCom("prosecuting","npc/combine_soldier/vo/prosecuting.wav")
addCom("sweepingin","npc/combine_soldier/vo/sweepingin.wav")
addCom("displace","npc/combine_soldier/vo/displace.wav")
addCom("displace2","npc/combine_soldier/vo/displace2.wav")
addCom("ghost2","npc/combine_soldier/vo/ghost2.wav")
addCom("ripcord2","npc/combine_soldier/vo/ripcord.wav")
addCom("flaredown","npc/combine_soldier/vo/flaredown.wav")
addCom("sundown","npc/combine_soldier/vo/flaredown.wav")
addCom("secure","npc/combine_soldier/vo/secure.wav")
addCom("suppressing","npc/combine_soldier/vo/suppressing.wav")
addCom("quicksand","npc/combine_soldier/vo/quicksand.wav")
addCom("stayalert","npc/combine_soldier/vo/stayalert.wav")
addCom("overwatch","npc/combine_soldier/vo/overwatch.wav")
addCom("sharpzone","npc/combine_soldier/vo/sharpzone.wav")
addCom("yes3","npc/combine_soldier/vo/affirmative2.wav")
addCom("alert","npc/combine_soldier/vo/alert1.wav")
addCom("arrested","npc/combine_soldier/vo/contained.wav")
addCom("readyweapons","npc/combine_soldier/vo/readyweapons.wav")
addCom("engaging","npc/combine_soldier/vo/engaging.wav")
addCom("delivered","npc/combine_soldier/vo/delivered.wav")
addCom("cover","npc/combine_soldier/vo/coverhurt.wav")
addCom("storm","npc/combine_soldier/vo/storm.wav")
addCom("onedown","npc/combine_soldier/vo/onedown.wav")
addCom("contact","npc/combine_soldier/vo/contact.wav")
addCom("flatline","npc/combine_soldier/vo/flatline.wav")
addCom("helix","npc/combine_soldier/vo/helix.wav")
addCom("gosharp","npc/combine_soldier/vo/gosharp.wav")
addCom("degrees","npc/combine_soldier/vo/degrees.wav")
addCom("sector","npc/combine_soldier/vo/degrees.wav")
addCom("closing","npc/combine_soldier/vo/closing.wav")
addCom("copythat","npc/combine_soldier/vo/copythat.wav")
addCom("yes4","npc/combine_soldier/vo/affirmative.wav")
addCom("shadow","npc/combine_soldier/vo/shadow.wav")
addCom("hurricane","npc/combine_soldier/vo/hurricane.wav")
addCom("range","npc/combine_soldier/vo/range.wav")
addCom("sweeper","npc/combine_soldier/vo/sweeper.wav")
addCom("movein","npc/combine_soldier/vo/movein.wav")
addCom("ranger","npc/combine_soldier/vo/ranger.wav")
addCom("bearing","npc/combine_soldier/vo/bearing.wav")
addCom("grid","npc/combine_soldier/vo/grid.wav")
addCom("coverme","npc/combine_soldier/vo/coverme.wav")
addCom("flush","npc/combine_soldier/vo/flush.wav")
addCom("closing2","npc/combine_soldier/vo/flush.wav")
addCom("razor","npc/combine_soldier/vo/razor.wav")
addCom("nova","npc/combine_soldier/vo/nova.wav")
addCom("apex","npc/combine_soldier/vo/apex.wav")
addCom("freeman3","npc/combine_soldier/vo/freeman3.wav")
addCom("echo","npc/combine_soldier/vo/echo.wav")
addCom("nomad","npc/combine_soldier/vo/nomad.wav")
addCom("cleaned","npc/combine_soldier/vo/nomad.wav")
addCom("star","npc/combine_soldier/vo/star.wav")
addCom("spear","npc/combine_soldier/vo/spear.wav")
addCom("kilo","npc/combine_soldier/vo/kilo.wav")
addCom("hunter","npc/combine_soldier/vo/hunter.wav")
addCom("dagger","npc/combine_soldier/vo/dagger.wav")
addCom("mace","npc/combine_soldier/vo/mace.wav")
addCom("payback","npc/combine_soldier/vo/payback.wav")
addCom("boomer","npc/combine_soldier/vo/boomer.wav")
addCom("striker","npc/combine_soldier/vo/striker.wav")
addCom("slash","npc/combine_soldier/vo/slash.wav")
addCom("ion","npc/combine_soldier/vo/ion.wav")
addCom("reaper","npc/combine_soldier/vo/reaper.wav")
addCom("slam","npc/combine_soldier/vo/reaper.wav")
addCom("scar","npc/combine_soldier/vo/scar.wav")
addCom("judge","npc/combine_soldier/vo/judge.wav")
addCom("stab","npc/combine_soldier/vo/stab.wav")
addCom("ice","npc/combine_soldier/vo/ice.wav")
addCom("savage","npc/combine_soldier/vo/savage.wav")
addCom("ghost","npc/combine_soldier/vo/ghost.wav")
addCom("phantom","npc/combine_soldier/vo/phantom.wav")
addCom("stinger","npc/combine_soldier/vo/phantom.wav")
addCom("leader","npc/combine_soldier/vo/leader.wav")
addCom("turnoncoms","npc/combine_soldier/vo/on1.wav")
addCom("turnoncoms2","npc/combine_soldier/vo/on2.wav")
addCom("swift","npc/combine_soldier/vo/swift.wav")
addCom("sword","npc/combine_soldier/vo/sword.wav")
addCom("target","npc/combine_soldier/vo/target.wav")
addCom("targetblackout","npc/combine_soldier/vo/targetblackout.wav")
addCom("targetcompromisedmovein","npc/combine_soldier/vo/targetcompromisedmovein.wav")
addCom("targetcontactat","npc/combine_soldier/vo/targetcontactat.wav")
addCom("targetineffective","npc/combine_soldier/vo/targetineffective.wav")
addCom("targetisat","npc/combine_soldier/vo/targetisat.wav")
addCom("targetmyradial","npc/combine_soldier/vo/targetmyradial.wav")
addCom("target1","npc/combine_soldier/vo/targetone.wav")
addCom("teamdeployed","npc/combine_soldier/vo/teamdeployedandscanning.wav")
addCom("wrapitup","npc/combine_soldier/vo/thatsitwrapitup.wav")
addCom("tracker","npc/combine_soldier/vo/tracker.wav")
addCom("uniform","npc/combine_soldier/vo/uniform.wav")
addCom("unitisclosing","npc/combine_soldier/vo/unitisclosing.wav")
addCom("unitisinbound","npc/combine_soldier/vo/unitisinbound.wav")
addCom("unitismovingin","npc/combine_soldier/vo/unitismovingin.wav")
addCom("vamp","npc/combine_soldier/vo/vamp.wav")
addCom("viscon","npc/combine_soldier/vo/vamp.wav")
addCom("visualonexogens","npc/combine_soldier/vo/visualonexogens.wav")
addCom("weaponsoffsafe","npc/combine_soldier/vo/weaponsoffsafeprepforcontact.wav")
addCom("weareinaninfestationzone","npc/combine_soldier/vo/weareinaninfestationzone.wav")
addCom("wehavefreeparasites","npc/combine_soldier/vo/wehavefreeparasites.wav")
addCom("wehavenontaggedviromes","npc/combine_soldier/vo/wehavenontaggedviromes.wav")
addCom("winder","npc/combine_soldier/vo/winder.wav")
addCom("get in here","sound/vo/trainyard/ba_inhere01.wav")
addCom("go","sound/vo/trainyard/ba_goon.wav")
addCom("I said move","sound/vo/trainyard/ba_move01.wav")
addCom("backup","sound/vo/trainyard/ba_backup.wav")
addCom("get in","sound/vo/trainyard/ba_getin.wav")
addCom("no im good","sound/vo/trainyard/ba_noimgood.wav")
addCom("now","sound/vo/trainyard/ba_thatbeer01.wav")
addCom("beer2","sound/vo/trainyard/ba_thatbeer02.wav")

hook.Add("PlayerSay","cpVoice",function(ply,text,public)

    text = string.lower(text)

    for k,v in pairs ( cpVoicesTeam ) do
        if ( team.GetName(ply:Team())==v ) then
        
		if(cpComs[text]) then
            ply:EmitSound(cpComs[text])  
			return text
        end              
        else end
    end
end )

--#NoSimplerr#
